services:
  api:
    build: .
    container_name: brisanet-backend
    depends_on:
      - db
    ports:
      - '3333:3333'
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules

  db:
    image: postgres:13
    container_name: brisanet-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=BrisanetDB
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  agent:
    image: portainer/agent
    container_name: brisanet-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

  portainer:
    image: portainer/portainer-ce
    container_name: brisanet-portainer
    command: -H tcp://agent:9001 --tlsskipverify
    ports:
      - '9000:9000'
    volumes:
      - portainer_data:/data

volumes:
  postgres_data:
  portainer_data:
